

# This file was *autogenerated* from the file legendre_tester.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_1000 = Integer(1000)
f = open("tangencies.txt")

has_zero = False
has_neg_one = False
has_one = False

out_t = open('tangencies_kronecker.txt','w')

while True:
    line = f.readline().strip()
    if line == '':
        break
    a = float(line[:line.find(' ')])
    b = float(line[line.find(' ')+_sage_const_1 :])
    #if gcd(a,b)>1:
    #    continue
    if a == _sage_const_0  or b == _sage_const_0 :
        continue


    if a%_sage_const_4 ==_sage_const_1 :
        chi = kronecker(a+b,a)
    elif a%_sage_const_4 ==_sage_const_3 :
        chi = kronecker(-a-b,a)
    else:
        chi = _sage_const_1000 

    if chi == _sage_const_0 :
        has_zero = True
    elif chi == _sage_const_1 :
        has_one = True
    elif chi == -_sage_const_1 :
        has_neg_one = True
    if chi != _sage_const_0 :
        out_t.write('{:<15s} {:<10s}'.format(str(int(a%_sage_const_4 ))+': '+str(int(a))+' '+str(int(b)),str(chi))+'\n')
    


out_t.close()

if has_zero:
    print("Some of the tangent circles have kronecker symbol 0")
if has_neg_one:
    print("Some of the tangent circles have kronecker symbol -1")
if has_one:
    print("Some of the tangent circles have kronecker symbol 1")

